services:
  mongo_db:
    image: mongo:latest
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - type: tmpfs
        target: /data/db
    networks:
      - mongodb_network

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - type: tmpfs
        target: /data
    networks:
      - mongodb_network

volumes:
  db:
  
networks:
  mongodb_network: